# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uRqlj1TGCGscKMr7_0sKkjzqY1o-5x6d
"""

!pip install gradio transformers torch scikit-learn PyPDF2 pdfplumber numpy nltk sentencepiece
!pip install -q gradio-themes

print("All packages installed successfully!")

# Cell 2: StudyBuddy - Complete Document Q&A System
import gradio as gr
from transformers import pipeline
import PyPDF2
import pdfplumber
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
import re

class DocumentProcessor:
    def __init__(self, chunk_size=400, chunk_overlap=50):
        self.chunk_size = chunk_size
        self.chunk_overlap = chunk_overlap

    def load_document(self, file_obj, pasted_text):
        """Load document from file or pasted text"""
        text = ""

        if file_obj is not None:
            try:
                if file_obj.name.endswith('.pdf'):
                    text = self._extract_from_pdf(file_obj)
                elif file_obj.name.endswith('.txt'):
                    content = file_obj.read()
                    if hasattr(content, 'decode'):
                        text = content.decode('utf-8')
                    else:
                        text = str(content)
            except Exception as e:
                return f"Error reading file: {str(e)}"
        elif pasted_text and pasted_text.strip():
            text = pasted_text

        return text

    def _extract_from_pdf(self, file_obj):
        """Extract text from PDF using multiple methods"""
        text = ""
        try:
            # Try pdfplumber first (better for most PDFs)
            with pdfplumber.open(file_obj) as pdf:
                for page in pdf.pages:
                    page_text = page.extract_text()
                    if page_text:
                        text += page_text + "\n"
        except Exception as e:
            # Fallback to PyPDF2
            try:
                file_obj.seek(0)  # Reset file pointer
                pdf_reader = PyPDF2.PdfReader(file_obj)
                for page in pdf_reader.pages:
                    page_text = page.extract_text()
                    if page_text:
                        text += page_text + "\n"
            except Exception as e2:
                return f"Error extracting PDF text: {str(e2)}"

        if not text.strip():
            return "Error: No text could be extracted from the PDF file."

        return text

    def chunk_document(self, text):
        """Split document into overlapping chunks for better context"""
        if not text or not text.strip():
            return []

        # Clean text
        text = re.sub(r'\s+', ' ', text).strip()

        if len(text) < 100:
            return [text]

        # Split into paragraphs first (better for context)
        paragraphs = re.split(r'\n\s*\n', text)
        chunks = []

        for paragraph in paragraphs:
            paragraph = paragraph.strip()
            if not paragraph:
                continue

            if len(paragraph) <= self.chunk_size:
                chunks.append(paragraph)
            else:
                # Split long paragraphs into sentences
                sentences = re.split(r'[.!?]+', paragraph)
                sentences = [s.strip() for s in sentences if s.strip()]

                current_chunk = ""
                for sentence in sentences:
                    if len(current_chunk) + len(sentence) <= self.chunk_size:
                        if current_chunk:
                            current_chunk += " " + sentence
                        else:
                            current_chunk = sentence
                    else:
                        if current_chunk:
                            chunks.append(current_chunk)
                        current_chunk = sentence

                if current_chunk:
                    chunks.append(current_chunk)

        return chunks

class TFIDFRetriever:
    def __init__(self):
        self.vectorizer = TfidfVectorizer(
            stop_words='english',
            max_features=5000,
            ngram_range=(1, 2)
        )
        self.chunks = []
        self.tfidf_matrix = None

    def index_chunks(self, chunks):
        """Build TF-IDF index from document chunks"""
        if not chunks:
            self.chunks = []
            self.tfidf_matrix = None
            return

        self.chunks = chunks
        try:
            self.tfidf_matrix = self.vectorizer.fit_transform(chunks)
        except Exception as e:
            print(f"Error in indexing: {e}")
            self.tfidf_matrix = None

    def get_relevant_chunks(self, question, top_k=3):
        """Retrieve most relevant chunks for any question"""
        if not self.chunks or self.tfidf_matrix is None:
            return []

        try:
            question_vec = self.vectorizer.transform([question])
            similarities = cosine_similarity(question_vec, self.tfidf_matrix).flatten()
            top_indices = similarities.argsort()[-top_k:][::-1]

            relevant_chunks = []
            for idx in top_indices:
                if similarities[idx] > 0.05:  # Lower threshold for more results
                    relevant_chunks.append({
                        'chunk': self.chunks[idx],
                        'similarity': similarities[idx],
                        'chunk_id': idx
                    })

            return relevant_chunks
        except Exception as e:
            print(f"Error in retrieval: {e}")
            return []

class StudyBuddy:
    def __init__(self):
        print("🚀 Starting StudyBuddy...")
        try:
            # Load QA model - using a smaller model for faster loading
            self.qa_pipeline = pipeline(
                "question-answering",
                model="distilbert-base-cased-distilled-squad"
            )
            # Load summarization model
            self.summarizer = pipeline(
                "summarization",
                model="facebook/bart-large-cnn"
            )
            print("✅ AI models loaded successfully!")
        except Exception as e:
            print(f"⚠️ Using fallback models: {e}")
            try:
                self.qa_pipeline = pipeline("question-answering")
                self.summarizer = pipeline("summarization")
            except:
                print("❌ Could not load any models")

        self.retriever = TFIDFRetriever()
        self.document_processor = DocumentProcessor()
        self.current_document = ""

    def process_document(self, file_obj, pasted_text):
        """Process any document for Q&A"""
        try:
            self.current_document = self.document_processor.load_document(file_obj, pasted_text)

            # Check for errors
            if not self.current_document.strip():
                return "❌ Please upload a PDF/TXT file or paste some text.", gr.update(visible=False)

            if "Error" in self.current_document:
                return self.current_document, gr.update(visible=False)

            # Process document into chunks
            chunks = self.document_processor.chunk_document(self.current_document)
            self.retriever.index_chunks(chunks)

            # Show statistics
            word_count = len(self.current_document.split())
            chunk_count = len(chunks)

            status = f"✅ **Document Ready for Questions!**\n\n"
            status += f"📊 **Document Analysis:**\n"
            status += f"• **Words:** {word_count}\n"
            status += f"• **Sections:** {chunk_count}\n"
            status += f"• **Characters:** {len(self.current_document)}\n\n"
            status += f"🎯 **You can now ask ANY questions about this document!**\n"
            status += f"• Ask about specific concepts\n• Request explanations\n• Seek definitions\n• Ask for lists or comparisons"

            return status, gr.update(visible=True)

        except Exception as e:
            return f"❌ Error: {str(e)}", gr.update(visible=False)

    def answer_question(self, question):
        """Answer ANY question about the document"""
        if not question or not question.strip():
            return "❌ Please enter a question.", ""

        if not self.retriever.chunks:
            return "❌ Please process a document first.", ""

        try:
            # Get relevant document sections
            relevant_chunks = self.retriever.get_relevant_chunks(question, top_k=4)

            if not relevant_chunks:
                return self._suggest_alternative_questions(question), ""

            # Try to find answer in relevant chunks
            best_answer = None
            best_score = 0
            best_chunk = None

            for chunk_info in relevant_chunks:
                try:
                    # Use the QA model to find exact answer
                    result = self.qa_pipeline(
                        question=question,
                        context=chunk_info['chunk']
                    )

                    if result['score'] > best_score:
                        best_score = result['score']
                        best_answer = result['answer']
                        best_chunk = chunk_info
                except Exception as e:
                    continue

            if best_answer and best_score > 0.1:
                return self._format_success_response(question, best_answer, best_score, best_chunk, relevant_chunks)
            else:
                return self._suggest_alternative_questions(question), ""

        except Exception as e:
            return f"❌ Error processing your question: {str(e)}", ""

    def _suggest_alternative_questions(self, original_question):
        """Suggest alternative questions when no answer is found"""
        suggestions = [
            "Try asking about specific concepts mentioned in the document",
            "Ask for explanations of key terms or ideas",
            "Request a summary of main points",
            "Ask 'What are the key findings?'",
            "Try 'Explain the main concepts'",
            "Ask 'What methods are described?'"
        ]

        response = f"❌ **No specific answer found for:** \"{original_question}\"\n\n"
        response += "💡 **Suggestions:**\n"
        for i, suggestion in enumerate(suggestions[:3], 1):
            response += f"{i}. {suggestion}\n"

        response += f"\n📖 The document contains {len(self.retriever.chunks)} sections of content. "
        response += "Try asking about different aspects of the material."

        return response

    def _format_success_response(self, question, answer, confidence, best_chunk, relevant_chunks):
        """Format a successful answer with details"""
        # Main answer
        answer_text = f"**🎯 Answer to Your Question**\n\n"
        answer_text += f"**❓ Question:** {question}\n\n"
        answer_text += f"**💡 Answer:** {answer}\n\n"
        answer_text += f"**📊 Confidence:** {confidence:.1%}\n\n"

        # Source context
        answer_text += f"**🔍 Source Context:**\n{best_chunk['chunk'][:400]}...\n\n"

        # Details section
        details = "**📖 Supporting Evidence from Document:**\n\n"
        for i, chunk_info in enumerate(relevant_chunks[:3]):
            is_primary = chunk_info['chunk_id'] == best_chunk['chunk_id']
            marker = "🎯 " if is_primary else "📄 "
            details += f"{marker}**Section {i+1}** (Relevance: {chunk_info['similarity']:.1%}):\n"
            details += f"{chunk_info['chunk'][:200]}...\n\n"

        return answer_text, details

    def generate_summary(self):
        """Generate document summary"""
        if not self.current_document.strip():
            return "❌ Please process a document first.", ""

        try:
            # Use appropriate context length
            if len(self.current_document) > 1024:
                context = self.current_document[:1024]
                note = "\n\n*Note: Summary based on the beginning of the document.*"
            else:
                context = self.current_document
                note = ""

            summary = self.summarizer(
                context,
                max_length=150,
                min_length=50,
                do_sample=False
            )[0]['summary_text']

            summary_output = f"**📄 Document Summary**\n\n{summary}{note}\n\n"
            summary_output += f"**📊 Original Document:** {len(self.current_document.split())} words"

            return summary_output, ""

        except Exception as e:
            return f"❌ Error generating summary: {str(e)}", ""

# Initialize StudyBuddy
study_buddy = StudyBuddy()

# Create the interface
def create_interface():
    with gr.Blocks(
        theme=gr.themes.Soft(
            primary_hue="blue",
            secondary_hue="purple"
        ),
        title="StudyBuddy - Document Q&A",
        css="""
        .gradio-container {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
        }
        """
    ) as demo:
        # Header
        gr.Markdown("""
        <div style="text-align: center; padding: 20px; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        border-radius: 15px; color: white; margin-bottom: 20px;">
            <h1 style="margin: 0; font-size: 2.8em;">🤖 StudyBuddy</h1>
            <p style="margin: 10px 0 0 0; font-size: 1.3em; opacity: 0.9;">
                Ask <strong>ANY Question</strong> About Your Documents - Get Instant Answers
            </p>
        </div>
        """)

        gr.Markdown("""
        ### 📚 How It Works:
        1. **Upload** a PDF/TXT file **OR** paste your text
        2. **Process** the document to analyze its content
        3. **Ask ANY question** and get AI-powered answers with sources
        """)

        with gr.Row(equal_height=False):
            # Input Column
            with gr.Column(scale=1):
                with gr.Group():
                    gr.Markdown("### 📁 1. Add Your Document")

                    file_input = gr.File(
                        label="Upload PDF or Text File",
                        file_types=[".pdf", ".txt"],
                        type="filepath"
                    )

                    gr.Markdown("<div style='text-align: center; margin: 10px 0;'><strong>― OR ―</strong></div>")

                    text_input = gr.Textbox(
                        label="Paste Document Text",
                        placeholder="Paste your textbook chapters, research papers, notes, articles, or any document text here...",
                        lines=8,
                        show_copy_button=True
                    )

                    process_btn = gr.Button(
                        "🚀 Analyze Document",
                        variant="primary",
                        size="lg"
                    )

                with gr.Group():
                    process_status = gr.Markdown(
                        label="Document Status",
                        value="*Waiting for document input...*"
                    )

            # Q&A Column
            with gr.Column(scale=1):
                with gr.Group():
                    gr.Markdown("###  2. Ask Any Question")

                    question_input = gr.Textbox(
                        label="Your Question About the Document",
                        placeholder="Examples:\n• 'What is the main argument in this document?'\n• 'Explain the key concepts on page 3'\n• 'What methods were used in the research?'\n• 'List the important findings'\n• 'Compare the different approaches mentioned'\n\nAsk anything about the content...",
                        lines=4,
                        show_copy_button=True
                    )

                    with gr.Row():
                        ask_btn = gr.Button("🎯 Get Answer", variant="primary", size="lg")
                        summarize_btn = gr.Button("📄 Summarize", variant="secondary")

                with gr.Group():
                    answer_output = gr.Markdown(
                        label="AI Answer",
                        value="**Your answers will appear here...**\n\nAsk any question about your document to get started!"
                    )

        # Details Section
        with gr.Row():
            with gr.Column():
                with gr.Group():
                    details_output = gr.Markdown(
                        label="Source Evidence & Context",
                        value="**Source details will appear here...**\n\nSee exactly where the answers come from with highlighted document sections."
                    )

        # Examples Section
        with gr.Row():
            with gr.Column():
                gr.Markdown("### 💡 Try These Question Types:")
                with gr.Row():
                    with gr.Column():
                        gr.Markdown("**🔍 Factual Questions**")
                        gr.Examples(
                            examples=[
                                ["What is the main topic?"],
                                ["Who are the key authors mentioned?"],
                                ["When was this research conducted?"],
                            ],
                            inputs=[question_input],
                            label=""
                        )

                    with gr.Column():
                        gr.Markdown("**📖 Explanatory Questions**")
                        gr.Examples(
                            examples=[
                                ["Explain the methodology used"],
                                ["How does this process work?"],
                                ["What are the underlying principles?"],
                            ],
                            inputs=[question_input],
                            label=""
                        )

                    with gr.Column():
                        gr.Markdown("**📊 Analytical Questions**")
                        gr.Examples(
                            examples=[
                                ["What are the advantages and disadvantages?"],
                                ["Compare the different approaches"],
                                ["What evidence supports the conclusions?"],
                            ],
                            inputs=[question_input],
                            label=""
                        )

        # Footer
        gr.Markdown("""
        <div style="text-align: center; margin-top: 30px; padding: 20px; background: #f8f9fa; border-radius: 10px;">
            <p style="margin: 0; color: #666;">
                <strong>StudyBuddy</strong> - Your AI Document Assistant • Ask Anything • Get Instant Answers
            </p>
        </div>
        """)

        # Event handlers
        process_btn.click(
            fn=study_buddy.process_document,
            inputs=[file_input, text_input],
            outputs=[process_status, summarize_btn]
        )

        ask_btn.click(
            fn=study_buddy.answer_question,
            inputs=[question_input],
            outputs=[answer_output, details_output]
        )

        summarize_btn.click(
            fn=study_buddy.generate_summary,
            inputs=[],
            outputs=[answer_output, details_output]
        )

        # Enter key support
        question_input.submit(
            fn=study_buddy.answer_question,
            inputs=[question_input],
            outputs=[answer_output, details_output]
        )

    return demo

# Launch the application
print(" StudyBuddy is starting...")
print("📖 Ready to answer ANY questions about your documents!")
demo = create_interface()
demo.launch(share=True, debug=True)